### ISSUE TITLE
Does not work behind proxy?

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#630]
We got a non-working report for CmisSync that involved a proxy.
TODO: Confirm that CmisSync works as intended behind a proxy, using the Internet Explorer proxy settings.

**Comment by barrynauta** [comment]
I have issues getting this to work as well, an HTTP connection via an RP succeeds, when trying to contact the same address via the same RP, I get authentication failures

DotCMIS.Exceptions.CmisRuntimeException: Proxy Authentication Required

**Comment by nicolas-raoul** [comment]
@barrynauta: I think I fixed this in the latest version, could you please try with https://bitbucket.org/aegif/cmissync/downloads/CmisSync.2.6.2.0.exe ?
Thanks for your feedback!

**Comment by barrynauta** [comment]
Hello,

First of all, thanks for the fast feedback!
Yes, I meant Reverse Proxy, indeed.

The proxy problems seem to have disappeared (I cannot confirm a 100% that it works, since we still face some other issues, but they seem to be related to our platform)

So, thanks again for the fast feedback AND resolution!

**Comment by nicolas-raoul** [comment]
Hello Barry,

Great to know that it works now, feel free to create new issue reports if you encounter any other problem.

Cheers!
Nicolas
